
spring:
  application:
    name: service-register

  datasource:
    url: jdbc:mysql://localhost:3306/student_registration
    username: root
    password: Sunny@799528
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update   # or create, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
server:
  port: 8082
